### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by JvGinkel** [mpdroog/stored#2]
* IHAVE ondersteuning (low prio)

* Meerder mount points / schijven
* inode limiet aantal files in een map (md5 messageid hash verdelen in sub mappen)
* HTTP call voor verwijderen van message-id(s) (hash/array)
* Opruim mechanisme bij X-GB. (Apart process welke de storage/mount points in de gaten houd en opruimt)
Op een storage server staan nu ongeveer 300miljoen+ message-ids

* Bij een ontvangend message-id schrijven naar /news/spool/incomming/$datum/$db.formaat.iets
messageid in database

Cleanup daemon leest oudste db uit en verwijderd de message-ids via http call bij stored. En verwijderd daarna de $datum map incl de database daarin.

```
storage:
  disk1:
    mountpoint: /news/spool/disk1
    minfree: 100g
  disk2:
    mountpoint: /news/spool/disk2
    minfree: 100g
```
```
/news/spool/disk1/md5:16/md5:32/msgid.txt
/news/spool/disk1/abcdef/012345/msgid.txt
/news/spool/disk1/678901/012345/msgid.txt
/news/spool/disk1/678901/abcdef/msgid.txt
/news/spool/disk2/md5:16/md5:32/msgid.txt

```
